### ISSUE TITLE
Question Container

### ISSUE THREAD

**Issue by ShaneKeney** [ShaneKeney/Yodrivia#11]
Main page content container for user generated questions to appear or questions generated by the API call
- Include cards for each question before/after they have been yodaified
- button for deleting individual questions for easy removal.

**Comment by Lmgom875** [comment]
I take this one.

**Comment by Lmgom875** [comment]
I going to create a Div / Card with flip feature with the anwser and the original question (without yodaified) on the back side. I start working on that let me know if sound good?
